alias cb='curl -o bootstrap.sh https://raw.githubusercontent.com/realulim/Bornemisza/master/salt/bootstrap.sh'
alias cbapp='curl -o bootstrap-bornemisza.sh https://raw.githubusercontent.com/realulim/Bornemisza/master/salt/app/bootstrap-bornemisza.sh'
alias cbdb='curl -o bootstrap-bornemisza.sh https://raw.githubusercontent.com/realulim/Bornemisza/master/salt/db/bootstrap-bornemisza.sh'
alias e='nano -w'
alias ebr='nano -w /etc/profile.d/bash.sh'
alias h='history'
alias ipdown='ip link set dummy1 down'
alias ipup='ip link set dummy1 up'
alias l='ls -lah'
alias lt='l -rt'
alias p-='systemctl stop payara'
alias p+='systemctl start payara'
alias rm='rm -i'
alias sbr='source /etc/profile.d/bash.sh'
alias sc='salt-call'
alias x='exit'

PS1="\u@\H:\w => ";
